name: VLNBERT-test-baseline-navgpt2-hsic

vlnbert: prevalent

submit: 0
test_only: 0

train: feature
load: snap/VLNBERT-train-Surrogate_NavGPT2/state_dict/best_val72_navgpt2
# loadmask: snap/VLNBERT-train-mask-navgpt-025-24vp/state_dict/LAST_iter3000
loadmask: snap/VLNBERT-train-mask-navgpt2-05-3/state_dict/LAST_iter4000

features: places365
maxAction: 15
batchSize: 1
feedback: sample
lr: 1e-5
iters: 300000
optim: adamW

ml_weight: 0.20
maxInput: 80
angle_feat_size: 128
featdropout: 0.4
dropout: 0.5

target_agent: NavGPT2
val_set_custom: NavGPT2_30_scenes_processed_merged # env for NavGPT2
val_set_custom_surr: NavGPT2_30_scenes_processed_merged # env for Xagent

feature_level_baseline: hsic

update_inference: inference
