name: VLNBERT-test-baseline-mapgpt-test-og

vlnbert: prevalent

submit: 0
test_only: 0

train: feature
load: snap/VLNBERT-train-Surrogate/state_dict/best_val72
# loadmask: snap/VLNBERT-train-mask-mapgpt/0.5mask_bs8/LAST_iter2000
loadmask: snap/VLNBERT-train-mask-mapgpt/finetune/LAST_iter160  # 160

features: places365
maxAction: 15
batchSize: 1
feedback: sample
lr: 1e-5
iters: 300000
optim: adamW

ml_weight: 0.20
maxInput: 80
angle_feat_size: 128
featdropout: 0.4
dropout: 0.5

target_agent: MapGPT
val_set_custom: val72 # env for MapGPT
val_set_custom_surr: MapGPT_72_scenes_processed # env for Xagent

feature_level_baseline: IG
