name: VLNBERT-test-navgpt-ensemble

vlnbert: prevalent

submit: 0
test_only: 0

# train: feature
train: feature_bagging
load: snap/VLNBERT-train-Bagging_NavGPT/state_dict/
loadmask: snap/VLNBERT-train-mask-navgpt-025-24vp/state_dict/LAST_iter3000

features: places365_24vp
maxAction: 10
batchSize: 1
feedback: sample
lr: 1e-5
iters: 300000
optim: adamW

ml_weight: 0.20
maxInput: 80
angle_feat_size: 128
featdropout: 0.4
dropout: 0.5

target_agent: NavGPT
# val_set_custom: val72 # env for MapGPT
val_set_custom: NavGPT_30_scenes_processed_merged # env for NavGPT
# val_set_custom_surr: NavGPT_72_scenes_processed # env for Xagent
val_set_custom_surr: NavGPT_30_scenes_processed_merged # env for Xagent


# Bagging specific parameters
bagging_agents: 5
bootstrap_ratio: 0.8


panoramic_horizontal_views: 8
vfov: 45

update_inference: update