name: VLNBERT-train-mask-navgpt-025-2-24vp

vlnbert: prevalent

aug: data/prevalent/prevalent_aug.json
test_only: 0

train: mask

features: places365_24vp
maxAction: 15
batchSize: 1
feedback: sample
lr: 1e-5
iters: 300
optim: adamW

ml_weight: 0.20
maxInput: 80
angle_feat_size: 128
featdropout: 0.4
dropout: 0.5

load: snap/VLNBERT-train-Surrogate_NavGPT_val_24vp/state_dict/best_val72_navgpt
loadmask: snap/VLNBERT-train-mask-navgpt-025-24vp/state_dict/LAST_iter3000

target_agent: NavGPT
val_set_custom: MapGPT_72_scenes_processed

training_set_custom: surrogate10_navgpt

# Panoramic view configuration for NavGPT surrogate model
panoramic_horizontal_views: 8
vfov: 45